/*
This migration creates the table activities.

activities groups consumptions into one activity.

it drops columns date and user_id from consumptions.


---------------------------------------------------------------------------------------

Backup strategies, in case something goes wrong:

1) pg_dump / psql

1.1) create backup:

pg_dump -t bellevue.consumptions ${PG_DSN_DEVELOPER} > consumptions.sql

1.2) restore:

psql ${PG_DSN_DEVELOPER} < consumptions.sql


2) SQL:

2.1) create backup:

CREATE TABLE bellevue.consumptions_backup
(LIKE bellevue.consumptions INCLUDING ALL);

INSERT INTO bellevue.consumptions_backup
SELECT * FROM bellevue.consumptions;

2.2) restore:

note: delete from vs truncate:
  truncate:    removes everything fast. does not fire delete triggers.
  delete from: row by row. can be rolled back.

TRUNCATE bellevue.consumptions;

INSERT INTO bellevue.consumptions
SELECT * FROM bellevue.consumptions_backup;
*/

begin;

alter table consumptions
add column activity_id int;


with ranked as (
  select id,
         dense_rank() over (order by "date", user_id) as activity_rank
    from consumptions
)
update consumptions t
   set activity_id = ranked.activity_rank
  from ranked
 where t.id = ranked.id;



create table bellevue.activities (
  id      int generated by default as identity
          primary key,
  user_id int
          references users(id),
  "date"  date not null
);

with activity_ids as (
    select distinct activity_id,
           user_id,
           date
      from consumptions
)
insert into activities (id, user_id, date)
select activity_id, user_id, date
from activity_ids;


select setval(
  pg_get_serial_sequence('bellevue.activities', 'id'),
  (select max(id) from bellevue.activities),
  true
);


alter table bellevue.consumptions
add constraint consumptions_activity_id_fkey
foreign key (activity_id)
references bellevue.activities(id);


alter table consumptions
drop column user_id,
drop column "date";

commit;
