BEGIN;
drop table bellevue.users cascade;
drop table bellevue.price_categories cascade;
drop table bellevue.taxes cascade;
drop table bellevue.financial_accounts cascade;
drop table bellevue.products cascade;
drop table bellevue.product_form_order cascade;
drop table bellevue.comments cascade;
drop table bellevue.invoices_v2 cascade;
drop table bellevue.consumptions cascade;
drop table bellevue.sessions cascade;
COMMIT;
