BEGIN;
ALTER DATABASE bellevue OWNER TO bellevue;
ALTER SCHEMA bellevue OWNER TO bellevue;
DROP SCHEMA bellevue;
DROP ROLE dev;
DROP OWNED BY developer;
DROP ROLE developer;
DROP OWNED BY app;
DROP ROLE app;
DROP ROLE application;
COMMIT;
